# Netlify config for deploying the React client and proxying API requests

[build]
  publish = "react-client/dist"
  command = "npm ci --prefix react-client && npm run build --prefix react-client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Route API requests to Netlify Function

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/categories"
  to = "/.netlify/functions/api/categories"
  status = 200
  force = true

[[redirects]]
  from = "/tasks/*"
  to = "/.netlify/functions/api/tasks/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/config/*"
  to = "/.netlify/functions/api/config/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200
  force = true

# Sensible default headers
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# SPA fallback for React Router (must be after API redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
